import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
  	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  return (
	<html lang="en" className="flex flex-col justify-center text-center">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<h1 className="text-3xl font-bold underline">Arcana Haven Prototype</h1>
				<nav>
					<p className="text-xl font-bold">Personal</p>
					<ul>
						<li>Reading Collection</li>
						<li>Sign Out</li>
					</ul>
					<p className="text-xl font-bold">Tarot Readings</p>
					<ul>
						<li>General Tarot</li>
						<li>Ask a Question</li>
						<li>Yes/No Tarot</li>
					</ul>
					<p className="text-xl font-bold">Card Meanings</p>
					<ul>
						<li>Major Arcana</li>
						<li>Wands</li>
						<li>Cups</li>
						<li>Swords</li>
						<li>Pentacles</li>
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
